version: '2'
services:
    quadfi-app:
        image: quadfi
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://quadfi-mariadb:3306/quadfi
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    quadfi-mariadb:
        extends:
            file: mariadb.yml
            service: quadfi-mariadb
